### ISSUE TITLE
feature/cassandra_1 用

### ISSUE THREAD

**Issue by hidetarou2013** [hidetarou2013/SpringDataBaseSample#3]
# feature/cassandra_1 用

**Comment by hidetarou2013** [comment]
edit

```
<property name="hibernateProperties">
            <props>
                <prop key="hibernate.dialect">org.hibernate.ogm.dialect.cassandra.CassandraCQL2Dialect</prop>
                <prop key="hibernate.show_sql">true</prop>
                <prop key="hibernate.ogm.datastore.provider">org.hibernate.ogm.datastore.cassandra.impl.CassandraDatastoreProvider</prop>
                <prop key="hibernate.ogm.datastore.host">localhost</prop>
                <prop key="hibernate.ogm.datastore.port">9042</prop>
                <prop key="hibernate.ogm.datastore.database">spring_database</prop>
                <prop key="hibernate.search.lucene_version">LUCENE_CURRENT</prop>
                <prop key="hibernate.ogm.cassandra.url">jdbc:cassandra://localhost:9160</prop>
                <prop key="hibernate.ogm.cassandra.default_keyspace">spring_database</prop>
                <prop key="hibernate.ogm.cassandra.autogenerate">update</prop>

            </props>
</property>
```

error

```
ERROR: org.springframework.web.servlet.DispatcherServlet - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'departmentsListController' defined in file [C:\pleiades\pleiades-e4.5\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\SpringDataBaseSample\WEB-INF\classes\com\example\springdatabasesample\controller\DepartmentsListController.class]: Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.example.springdatabasesample.controller.DepartmentsListController
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1076)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:658)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:817)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.example.springdatabasesample.controller.DepartmentsListController
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1069)
	... 36 more
重大: StandardWrapper.Throwable [日 12 11 03:23:42 JST 2016]
重大: サーブレット appServlet に例外を割り当てます [日 12 11 03:23:42 JST 2016]

```

**Comment by hidetarou2013** [comment]
```
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.ogm.dialect.cassandra.CassandraCQL2Dialect] as strategy [org.hibernate.dialect.Dialect]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:128)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:155)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:136)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.constructDialect(DialectFactoryImpl.java:78)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:68)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:165)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1928)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBuilder.buildSessionFactory(LocalSessionFactoryBuilder.java:343)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:431)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBean.afte重大: StandardWrapper.Throwable [日 12 11 03:44:03 JST 2016]
rPropertiesSet(LocalSessionFactoryBean.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	... 48 more
```

**Comment by hidetarou2013** [comment]
エラー変わらず。。

**Comment by hidetarou2013** [comment]
tomcat8 起動時に起動しなくなる障害
@maekawa-PC

```
重大: A child container failed during start [月 12 12 10:50:06 JST 2016]
重大: A child container failed during start [月 12 12 10:50:06 JST 2016]
重大: The required Server component failed to start so Tomcat is unable to start. [月 12 12 10:50:06 JST 2016]
情報: Pausing ProtocolHandler ["http-nio-8080"] [月 12 12 10:50:06 JST 2016]
情報: Pausing ProtocolHandler ["ajp-nio-8009"] [月 12 12 10:50:06 JST 2016]
情報: サービス Catalina を停止します [月 12 12 10:50:06 JST 2016]
情報: Destroying ProtocolHandler ["http-nio-8080"] [月 12 12 10:50:06 JST 2016]
重大: Failed to destroy end point associated with ProtocolHandler ["http-nio-8080"] [月 12 12 10:50:06 JST 2016]
情報: Destroying ProtocolHandler ["ajp-nio-8009"] [月 12 12 10:50:06 JST 2016]
重大: Failed to destroy end point associated with ProtocolHandler ["ajp-nio-8009"] [月 12 12 10:50:06 JST 2016]
情報: Destroying Spring FrameworkServlet 'appServlet' [月 12 12 10:50:06 JST 2016]
INFO : org.springframework.web.context.support.XmlWebApplicationContext - Closing WebApplicationContext for namespace 'appServlet-servlet': startup date [Mon Dec 12 10:50:02 JST 2016]; parent: Root WebApplicationContext
情報: Closing Spring root WebApplicationContext [月 12 12 10:50:06 JST 2016]
INFO : org.springframework.web.context.support.XmlWebApplicationContext - Closing Root WebApplicationContext: startup date [Mon Dec 12 10:50:02 JST 2016]; root of context hierarchy
警告: The web application [databasesample] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered. [月 12 12 10:50:06 JST 2016]
警告: The web application [databasesample] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43) [月 12 12 10:50:06 JST 2016]
警告: The web application [databasesample] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505) [月 12 12 10:50:06 JST 2016]
重大: The web application [databasesample] created a ThreadLocal with key of type [org.apache.log4j.helpers.ThreadLocalMap] (value [org.apache.log4j.helpers.ThreadLocalMap@75055e92]) and a value of type [java.util.Hashtable] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. [月 12 12 10:50:06 JST 2016]

```

**Comment by hidetarou2013** [comment]
ちなみに、元ネタの「databaseSample」はちゃんと起動する。

もうひとつサーバ：Tomcat8 (Java8) (2)　作成しても結果は同じだった。

```
サーバー ローカル・ホスト での Tomcat8 (Java8) (2) は始動に失敗しました。
```

**Comment by hidetarou2013** [comment]
4.2.0.Final　でないと、Tomcat8起動ができなくなってしまうようだ。。。
Mavenのビルド自体は成功するんだけど、Tomcat8と関連するのかな。。

**Comment by hidetarou2013** [comment]
## そもそも「hibernate-core-4.3.6.Final」パッケージには、NoSQL系のDialectクラスは存在しなかった。


Originally in the "hibernate - core - 4.3.6. Final" package there was no NoSQL - based Dialect class.


```
 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は 8486-FACE です

 C:\Users\maekawa\Desktop\hibernate-core-4.3.6.Final-sources\org\hibernate\dialect のディレクトリ

2016/12/12  14:25    <DIR>          .
2016/12/12  14:25    <DIR>          ..
2014/07/09  23:07            27,304 AbstractHANADialect.java
2014/07/09  23:07            11,027 AbstractTransactSQLDialect.java
2014/07/09  23:07            31,223 Cache71Dialect.java
2014/07/09  23:03             2,571 ColumnAliasExtractor.java
2014/07/09  23:03            16,339 CUBRIDDialect.java
2014/07/09  23:07             1,777 DataDirectOracle9Dialect.java
2014/07/09  23:07             2,077 DB2390Dialect.java
2014/07/09  23:07             2,174 DB2400Dialect.java
2014/07/09  23:07            17,437 DB2Dialect.java
2014/07/09  23:07             7,568 DerbyDialect.java
2014/07/09  23:07             2,012 DerbyTenFiveDialect.java
2014/07/09  23:03             1,467 DerbyTenSevenDialect.java
2014/07/09  23:03             1,618 DerbyTenSixDialect.java
2014/07/09  23:07            93,509 Dialect.java
2014/07/09  23:07             1,947 FirebirdDialect.java
2014/07/09  23:03             5,115 FrontBaseDialect.java
2016/12/12  14:23    <DIR>          function
2014/07/09  23:07            17,884 H2Dialect.java
2014/07/09  23:03             1,539 HANAColumnStoreDialect.java
2014/07/09  23:03             1,580 HANARowStoreDialect.java
2014/07/09  23:07            22,612 HSQLDialect.java
2014/07/09  23:07             8,478 InformixDialect.java
2014/07/09  23:03             3,018 Ingres10Dialect.java
2014/07/09  23:07             5,151 Ingres9Dialect.java
2014/07/09  23:07            13,603 IngresDialect.java
2014/07/09  23:07             4,544 InterbaseDialect.java
2014/07/09  23:03             2,988 JDataStoreDialect.java
2014/07/09  23:03             2,289 LobMergeStrategy.java
2016/12/12  14:23    <DIR>          lock
2014/07/09  23:03             5,716 MckoiDialect.java
2014/07/09  23:07             9,729 MimerSQLDialect.java
2014/07/09  23:07             2,447 MySQL5Dialect.java
2014/07/09  23:03             1,466 MySQL5InnoDBDialect.java
2014/07/09  23:07            18,628 MySQLDialect.java
2014/07/09  23:03             1,438 MySQLInnoDBDialect.java
2014/07/09  23:03             1,355 MySQLMyISAMDialect.java
2014/07/09  23:03             2,098 Oracle10gDialect.java
2014/07/09  23:07            21,242 Oracle8iDialect.java
2014/07/09  23:07            14,827 Oracle9Dialect.java
2014/07/09  23:07             4,380 Oracle9iDialect.java
2014/07/09  23:07             3,598 OracleDialect.java
2014/07/09  23:03             4,051 OracleTypesHelper.java
2014/07/09  23:03             1,277 package.html
2016/12/12  14:23    <DIR>          pagination
2014/07/09  23:03             4,203 PointbaseDialect.java
2014/07/09  23:07             4,122 PostgresPlusDialect.java
2014/07/09  23:07            18,318 PostgreSQL81Dialect.java
2014/07/09  23:03             1,349 PostgreSQL82Dialect.java
2014/07/09  23:07             1,357 PostgreSQL9Dialect.java
2014/07/09  23:07             1,619 PostgreSQLDialect.java
2014/07/09  23:03             2,705 ProgressDialect.java
2014/07/09  23:07            16,529 RDMSOS2200Dialect.java
2014/07/09  23:03             2,859 ResultColumnReferenceStrategy.java
2014/07/09  23:03            10,447 SAPDBDialect.java
2014/07/09  23:03             4,584 SQLServer2005Dialect.java
2014/07/09  23:03             1,733 SQLServer2008Dialect.java
2014/07/09  23:03             1,968 SQLServer2012Dialect.java
2014/07/09  23:07             6,431 SQLServerDialect.java
2014/07/09  23:03             1,606 Sybase11Dialect.java
2014/07/09  23:03             1,919 SybaseAnywhereDialect.java
2014/07/09  23:03             4,460 SybaseASE157Dialect.java
2014/07/09  23:03            19,295 SybaseASE15Dialect.java
2014/07/09  23:03             2,048 SybaseDialect.java
2014/07/09  23:03             8,603 TeradataDialect.java
2014/07/09  23:07             8,401 TimesTenDialect.java
2014/07/09  23:03             5,421 TypeNames.java
2016/12/12  14:23    <DIR>          unique
2016/12/12  14:25                 0 zzz.txt
              64 個のファイル             531,080 バイト
               6 個のディレクトリ  1,790,552,203,264 バイトの空き領域

```
